apiVersion: v1
kind: Service
metadata:
  name: dyplomaapp-nginx
  namespace: dyplomaapp
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: dyplomaapp-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.app_service.nodeport }}
