apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplomaapp-nginx-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: diplomaapp-nginx
spec:
  replicas: {{ .Values.app_deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: diplomaapp-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: diplomaapp-nginx
    spec:
      containers:
      - name: diplomaapp-nginx
        image: {{ .Values.app_deployment.image.repository }}:{{ .Values.app_deployment.image.tag }}
        resources:
          requests:
            memory: {{ .Values.app_deployment.resources.requests.memory }}
            cpu: {{ .Values.app_deployment.resources.requests.cpu }}
          limits:
            memory: {{ .Values.app_deployment.resources.limits.memory }}
            cpu: {{ .Values.app_deployment.resources.limits.cpu }}
        ports:
        - containerPort: 80
