apiVersion: v1
kind: Service
metadata:
  name: diplomaapp-nginx
  namespace: diplomaapp
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: diplomaapp-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.app_service.nodeport }}
