---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: diploma-app
    release: {{ .Release.Name }}
  name: diploma-app-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diploma-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: diploma-app
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.app_deployment.repository }}:{{ .Values.app_deployment.tag | default .Values.image.tag }}"
          name: diploma-app
          ports:
            - containerPort: 80
              name: http
      restartPolicy: Always
