apiVersion: v1
kind: Service
metadata:
  name: diploma-app
spec:
  type: NodePort
  selector:
    app: diploma-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
