pipeline {
  agent any
  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
  }
  stages {
    stage('Get last tag') {
      steps {
        script {
          last_tag = sh(returnStdout: true, script: 'git tag --list --sort=-version:refname \"0*\" | head -n 1').trim()
        }
        echo "last_tag=$last_tag"
      }
    }
    stage('Docker Build') {
      steps {
        script {
          sh "docker build -t chuckberry321/diplomaapp:${last_tag} ."
        }
      }
    }
    stage('Dockerhub login') {
      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('Docker push') {
      steps {
        sh "docker push chuckberry321/diplomaapp:${last_tag}"
      }
    }
    stage('deploy app via helm') {
      steps {
        sh "helm upgrade netology ./diplomaapp/ --set app_deployment.image.tag=${last_tag} -n test-app --kubeconfig ~/config"
      }
    }   
  }
}
